### ISSUE TITLE
no output after this "model loaded!" 

### ISSUE THREAD

**Issue by GokulSakthivel** [2052sagar/PlantDiseaseDetection#1]
PlantDiseaseDetection-master$ python ui.py
0it [00:00, ?it/s]
WARNING:tensorflow:From /home/gokul/.local/lib/python2.7/site-packages/tflearn/initializations.py:119: __init__ (from tensorflow.
python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
model loaded!
Tkinter works fine but after click on analyse image nothing will happened!!

**Comment by GokulSakthivel** [comment]
def process_verify_data():
        verifying_data = []
        for img in tqdm(os.listdir(verify_dir)):
            path = os.path.join(verify_dir, img)
            img_num = img.split('.')[0]
            img = cv2.imread(path, cv2.IMREAD_COLOR)
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            verifying_data.append([np.array(img), img_num])
        np.save('verify_data.npy', verifying_data)
        return verifying_data


#what happened here it return empty list...?

**Comment by 2052sagar** [comment]
I have again viewed the code once bt there was no any problem. I think you are not getting output because of invalid directory where the image is kept. Please again see the code once and create the directory as in code or change the path in the code where you have image for verification

**Comment by 2052sagar** [comment]
I have again viewed the code once bt there was no any problem. I think you are not getting output because of invalid directory where the image is kept. Please again see the code once and create the directory as in code or change the path in the code where you have image for verification
