### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by JiangDing1995** [2052sagar/PlantDiseaseDetection#2]
1、what kind of plant it is in your train and test dataset?
2、in train dataset,does the first name of .jpg files such as"b , h , i , v" mean different kinds of diseases?And what is the name of the four diseases?

need your help and hope for your reply! Thank you !

**Comment by 2052sagar** [comment]
1. in my train and test dataset i used tomato plant.
2. for this project I used 4 different cases that may appear in tomato
plant and they are named as b, h, i, v. Here,
b = bacterial disease
h = healthy plant
l = lateblight disease
v = viral disease

**Comment by JiangDing1995** [comment]
Thanks!

**Comment by 2052sagar** [comment]
welcome :)
